#!/bin/bash

# init function for the squid service publisher, to export some variables

SQUID_PORT=${SQUID_PORT:-3128}
SQUID_HOST=${SQUID_HOST:-`hostname -f`}

SQUID_PID_FILE=${SQUID_PID_FILE:-/var/run/squid/squid.pid}

# Write to stdout - will be imported by the info provider

echo SQUID_PORT=$SQUID_PORT
echo SQUID_HOST=$SQUID_HOST
echo SQUID_PID_FILE=$SQUID_PID_FILE

