#!/bin/bash

# init function for the myproxy service publisher, to export some variables

# These can be overridden by external definitions of the variables,
# e.g. if the advertised host name should be an alias

MYPROXY_CONF=${MYPROXY_CONF:-/etc/myproxy-server.conf}

MYPROXY_HOST=${MYPROXY_HOST:-`hostname -f`}

MYPROXY_PORT=${MYPROXY_PORT:-7512}

# Write to stdout - will be imported by the info provider

echo MYPROXY_CONF=$MYPROXY_CONF
echo MYPROXY_HOST=$MYPROXY_HOST
echo MYPROXY_PORT=$MYPROXY_PORT

# myproxy doesn't seem to have a pid file, but the init.d script
# does create and remove this lock file

echo MYPROXY_PID_FILE=/var/lock/subsys/myproxy-server


