#!/bin/bash

# init function for the gridice service publisher, to export some variables

# The first two can be overridden by external definitions of the variables,
# e.g. if the advertised host name should be an alias

GRIDICE_HOST=${GRIDICE_HOST:-`hostname -f`}
GRIDICE_PORT=${GRIDICE_PORT:-2136}

# Write to stdout - will be imported by the info provider

echo GRIDICE_PORT=$GRIDICE_PORT
echo GRIDICE_HOST=$GRIDICE_HOST

# We seem to be stuck with having this hardwired
echo GRIDICE_PID_FILE=/opt/gridice/monitoring/gris/var/tmp/daemon-gridice-mds.pid

