#!/bin/bash

# init function for the WMProxy service publisher, to export some variables

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-/var/glite}

WMPROXY_PORT_DEFAULT=${WMPROXY_PORT:-7443}
WMPROXY_HOST_DEFAULT=${WMPROXY_HOST:-`hostname -f`}

WMPROXY_CONF=${WMPROXY_CONF:-${GLITE_LOCATION}/etc/glite_wms_wmproxy_httpd.conf}

# The greps here may be fragile

# eval here for safety, not currently needed
eval WMPROXY_PORT=`grep ^Listen $WMPROXY_CONF | cut -d" " -f2`
WMPROXY_PORT=${WMPROXY_PORT:-${WMPROXY_PORT_DEFAULT}}

eval WMPROXY_HOST=`grep ^ServerName $WMPROXY_CONF | cut -d" " -f2`
WMPROXY_HOST=${WMPROXY_HOST_1:-${WMPROXY_HOST_DEFAULT}}

# eval needed here because it needs a variable substitution
eval WMPROXY_PID_FILE=`grep ^PidFile $WMPROXY_CONF | cut -d" " -f2`
WMPROXY_PID_FILE=${WMPROXY_PID_FILE:-${GLITE_LOCATION_VAR}/httpd-wmproxy.pid}

# Write to stdout - will be imported by the info provider

echo WMPROXY_PORT=$WMPROXY_PORT
echo WMPROXY_HOST=$WMPROXY_HOST
echo WMPROXY_PID_FILE=$WMPROXY_PID_FILE

